name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via git pull
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ 22 }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            cd ~/www/portfolio.seanpierce.net
            git checkout -- .
            git pull origin master

            VERSION=$(git rev-parse HEAD)
            sed -i "s/scripts.js/scripts.js?v=$VERSION/g" index.html
            sed -i "s/dots.js/dots.js?v=$VERSION/g" index.html
            sed -i "s/index.css/index.css?v=$VERSION/g" index.html

          EOF